spring:
  application:
   name: room-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: room         
      username: root
      password: root
      authentication-database: admin  
logging:
  level:
    root: INFO
    com.example.room_service.filter: DEBUG
room: 
  seed:
   enabled: false